# Generated by Django 6.0.6 on 2026-06-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('category', models.CharField(choices=[('land', 'زمین صنعتی'), ('factory', 'کارخانه'), ('machinery', 'ماشین\u200cآلات'), ('import', 'واردات'), ('export', 'صادرات')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('status', models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('buy', 'خرید')], default='sale', max_length=10, verbose_name='نوع آگهی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.BigIntegerField(blank=True, null=True, verbose_name='قیمت (تومان)')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='مساحت (متر مربع)')),
                ('location', models.CharField(max_length=200, verbose_name='موقعیت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='listings/', verbose_name='تصویر')),
                ('contact', models.CharField(max_length=50, verbose_name='تلفن تماس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
