# Generated by Django 6.0.6 on 2026-06-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('land', 'زمین صنعتی'), ('factory', 'کارخانه'), ('machinery', 'ماشین\u200cآلات'), ('import', 'واردات'), ('export', 'صادرات'), ('product', 'محصولات')], max_length=20, verbose_name='دسته\u200cبندی'),
        ),
    ]
