# Generated by Django 6.0.6 on 2026-06-05 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر پروفایل')),
                ('bio', models.TextField(blank=True, verbose_name='معرفی')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='شرکت/سازمان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('membership', models.CharField(choices=[('free', 'رایگان'), ('gold', 'طلایی'), ('premium', 'ویژه')], default='free', max_length=20, verbose_name='نوع عضویت')),
                ('membership_expires', models.DateTimeField(blank=True, null=True, verbose_name='انقضای عضویت')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
            },
        ),
    ]
